name: Build check
on: push

env:
  IMAGE: github-actions-etrobocon2021

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: Create docker image tag
        run: |
          sudo apt-get install -y jq
          TAG=`curl \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/ETrobocon/etrobo/commits/master?per_page=1 | \
            jq '.sha' | \
            sed -e 's/"//g'`
          LATEST_TAG=`curl \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ github.token }}" \
            https://api.github.com/users/Takahiro55555/packages/container/github-actions-etrobocon2021/versions | \
            jq '.[0].metadata.container.tags' | \
            grep -vE '(latest)|\[|\]' | \
            sed -e 's/"//g' | \
            sed -e 's/,//g' | \
            sed -e 's/\s//g' || echo ''`
          IS_REBUILD_DOCKER_IMAGE='false'
          if [ -ne $TAG $LATEST_TAG ]; then
            IS_REBUILD_DOCKER_IMAGE='true'
          fi
          echo IS_REBUILD_DOCKER_IMAGE=$IS_REBUILD_DOCKER_IMAGE >> $GITHUB_ENV
          echo TAG=$TAG >> $GITHUB_ENV

      - name: Build and publish docker image
        if: ${{ env.IS_REBUILD_DOCKER_IMAGE == 'true' }}
        uses: matootie/github-docker@v3.1.0
        with:
          accessToken: ${{ secrets.PAT }}
          imageName: ${{ env.IMAGE }}
          tag: |
            latest
            ${{ env.TAG }}
          containerRegistry: true

      - name: ETRobocon build test
        run: |
          echo ${{ secrets.PAT }} | docker login ghcr.io -u Takahiro55555 --password-stdin
          docker pull ghcr.io/takahiro55555/github-actions-etrobocon2021
          docker run -v ${{ github.workspace }}:/tmp/etrobocon2021:rw ghcr.io/takahiro55555/github-actions-etrobocon2021
