name: Deploy GitHub Pages

on:
  push:
    # branches:
    #   - main

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        # with:
        #   ref: main

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: cd documents; npm install; npm run build --if-present -- --public-url "/etrobocon2021/" --no-scope-hoist

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./documents/dist
